version: '3'
services:
  calculator-backend:
    build: .
    ports:
      - 8089:8089
    restart: on-failure
#    volumes:
#      - api:/usr/src/app/
    depends_on:
      - mysql-service
    networks:
      - calculator-network


  mysql-service:
    image: mysql:8.0.20
#    container_name: mysql-service
    restart: always
    ports:
      - 3306:3306
    environment:
#      - MYSQL_ROOT_HOST=${DB_HOST}
#      - MYSQL_USER=${DB_USER}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
#    volumes:
#      - database_mysql:/var/lib/mysql
    networks:
      - calculator-network

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  calculator-network:
    driver: bridge
