spring:
  data:
    neo4j:
      username: neo4j
      password: password
      uri: bolt://localhost:7687
      use-native-types: "true"

logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt: DEBUG
